name: my-app
region: nyc
services:
  - name: web-service
    git:
      repo_clone_url: https://github.com/uriel122810/alarm
      branch: main
    github:
      repo: uriel122810/alarm
      branch: main
      deploy_on_push: true
    image:
      registry_type: DOCR
      registry: ghcr.io
      repository: uriel122810/alarm
      tag: latest
      digest: sha256:1234567890abcdef
      registry_credentials: "$your_username:$access_token"
      deploy_on_push:
        enabled: true
    gitlab:
      repo: uriel122810/alarm
      branch: main
      deploy_on_push: true
    dockerfile_path: ./Dockerfile
    build_command: npm install && npm run build
    run_command: npm start
    source_dir: ./web
    envs:
      - key: NODE_ENV
        value: production
        scope: RUN_TIME
        type: general
      - key: SECRET_KEY
        value: EV[1:zqiRIeaaYK/NqctZDYzy6t0pTrtRDeq8:wqGpZRrsKN5nPhWQrS479cfBiXT0WQ==]
        type: secret
    instance_count: 2
    autoscaling:
      min_instances: 1
      max_instances: 5
      metrics:
        cpu:
          percent: 75
    http_port: 5050
    health_check:
      initial_delay_seconds: 5
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 2
      failure_threshold: 3
      http_path: /api
      port: 5050
    internal_ports: [5050, 50]
    alerts:
      - rule: CPU_UTILIZATION
        disabled: false
        operator: GREATER_THAN
        value: 75
        window: FIVE_MINUTES
    log_destinations:
      - name: alarm-logger
        papertrail:
          endpoint: logs.papertrailapp.com:12345
        datadog:
          endpoint: logs.datadoghq.com:12345
          api_key: AIzaSyCsS-yjXOMlU9sf7JW2o6EKPwo49OGX8a8
        logtail:
          token: 123e4567-e89b-12d3-a456-426614174000
        open_search:
          endpoint: logs.alarm.com:12345
          basic_auth:
            user: doadmin
            password: 123456QWERT
          index_name: alarm-index
          cluster_name: alarm-cluster
    termination:
      drain_seconds: 30
      grace_period_seconds: 90
static_sites:
  - name: static-site
    git:
      repo_clone_url: https://github.com/uriel122810/alarm
      branch: main
    github:
      repo: uriel122810/alarm
      branch: main
      deploy_on_push: true
    gitlab:
      repo: uriel122810/alarm
      branch: main
      deploy_on_push: true
    dockerfile_path: ./Dockerfile
    build_command: npm install && npm run build
    source_dir: ./web
    output_dir: build
    index_document: index.html
    error_document: 404.html
    envs:
      - key: API_ENDPOINT
        value: https://github.com/uriel122810/alarm
        scope: RUN_TIME
        type: general
      - key: SECRET_KEY
        value: EV[1:zqiRIeaaYK/NqctZDYzy6t0pTrtRDeq8:wqGpZRrsKN5nPhWQrS479cfBiXT0WQ==]
        type: secret
    catchall_document: index.html
workers:
  - name: background-worker
    git:
      repo_clone_url: https://github.com/uriel122810/alarm
      branch: main
    github:
      repo: uriel122810/alarm
      branch: main
      deploy_on_push: true
    image:
      registry_type: DOCR
      registry: ghcr.io
      repository: uriel122810/alarm
      tag: latest
      digest: sha256:1234567890abcdef
      registry_credentials: "$your_username:$access_token"
      deploy_on_push:
        enabled: true
    gitlab:
      repo: uriel122810/alarm
      branch: main
      deploy_on_push: true
    dockerfile_path: ./Dockerfile
    build_command: npm install && npm run build
    run_command: npm start
    source_dir: ./web
    envs:
      - key: NODE_ENV
        value: production
        scope: RUN_TIME
        type: general
      - key: SECRET_KEY
        value: EV[1:zqiRIeaaYK/NqctZDYzy6t0pTrtRDeq8:wqGpZRrsKN5nPhWQrS479cfBiXT0WQ==]
        type: secret
    instance_count: 2
    autoscaling:
      min_instances: 1
      max_instances: 5
      metrics:
        cpu:
          percent: 75
    alerts:
      - rule: CPU_UTILIZATION
        disabled: false
        operator: GREATER_THAN
        value: 75
        window: FIVE_MINUTES
    log_destinations:
      - name: alarm-logger
        papertrail:
          endpoint: logs.papertrailapp.com:12345
        datadog:
          endpoint: logs.datadoghq.com:12345
          api_key: AIzaSyCsS-yjXOMlU9sf7JW2o6EKPwo49OGX8a8
        logtail:
          token: 123e4567-e89b-12d3-a456-426614174000
        open_search:
          endpoint: logs.alarm.com:12345
          basic_auth:
            user: doadmin
            password: 123456qwert
          index_name: alarm-index
          cluster_name: alarm-cluster
    termination:
      drain_seconds: 30
      grace_period_seconds: 90
jobs:
    git:
      repo_clone_url: https://github.com/uriel122810/alarm
      branch: main
    github:
      repo: uriel122810/alarm
      branch: main
      deploy_on_push: true
    image:
      registry_type: DOCR
      registry: ghcr.io
      repository: uriel122810/alarm
      tag: latest
      digest: sha256:1234567890abcdef
      registry_credentials: "$your_username:$access_token"
      deploy_on_push:
        enabled: true
    gitlab:
      repo: uriel122810/alarm
      branch: main
      deploy_on_push: true
    dockerfile_path: ./Dockerfile
    build_command: npm install && npm run build
    run_command: npm start
    source_dir: ./web
    envs:
      - key: NODE_ENV
        value: production
        scope: RUN_TIME
        type: general
      - key: SECRET_KEY
        value: EV[1:zqiRIeaaYK/NqctZDYzy6t0pTrtRDeq8:wqGpZRrsKN5nPhWQrS479cfBiXT0WQ==]
        type: secret
    instance_count: 2
    kind: PRE_DEPLOY
    alerts:
      - rule: CPU_UTILIZATION
        disabled: false
        operator: GREATER_THAN
        value: 75
        window: FIVE_MINUTES
    log_destinations:
      - name: alarm-logger
        papertrail:
          endpoint: logs.papertrailapp.com:12345
        datadog:
          endpoint: logs.datadoghq.com:12345
          api_key: AIzaSyCsS-yjXOMlU9sf7JW2o6EKPwo49OGX8a8
        logtail:
          token:  123e4567-e89b-12d3-a456-426614174000
        open_search:
          endpoint: logs.alarm.com:12345
          basic_auth:
            user: doadmin
            password: 123456QWERT
          index_name: alarm-index
          cluster_name: alarm-cluster
    termination:
      drain_seconds: 30
      grace_period_seconds: 90
functions:
  - name: alarm-function
    git:
      repo_clone_url: https://github.com/uriel122810/alarm
      branch: main
    github:
      repo: uriel122810/alarm
      branch: main
      deploy_on_push: true
    gitlab:
      repo: uriel122810/alarm
      branch: main
      deploy_on_push: true
    source_dir: ./web
    envs:
      - key: NODE_ENV
        value: production
        scope: RUN_TIME
        type: general
      - key: SECRET_KEY
        value: EV[1:zqiRIeaaYK/NqctZDYzy6t0pTrtRDeq8:wqGpZRrsKN5nPhWQrS479cfBiXT0WQ==]
        type: secret
    alerts:
      - rule: CPU_UTILIZATION
        disabled: false
        operator: GREATER_THAN
        value: 75
        window: FIVE_MINUTES
    log_destinations:
      - name: alarm-logger
        papertrail:
          endpoint: logs.papertrailapp.com:12345
        datadog:
          endpoint: logs.datadoghq.com:12345
          api_key: 82d168fdae72372ec79408dd22912d97
        logtail:
          token: 123e4567-e89b-12d3-a456-426614174000
        open_search:
          endpoint: logs.alarm.com:12345
          basic_auth:
            user: doadmin
            password: 123456qwert
          index_name: alarm.index
          cluster_name: alarm-cluster
    termination:
      drain_seconds: 30
      grace_period_seconds: 90
databases:
  - name: postgres-db
    engine: PG
    version: "13"
    production: true
    cluster_name: alarm-cluster
    db_name: alarm-db
    db_user: alarm-user
domains:
  - domain: app.alarm.com
    type: primary
    wildcard: true
    zone: alarm.com
    minimum_tls_version: 1.2
envs:
  - key: NODE_ENV
    value: production
    scope: RUN_TIME
    type: general
  - key: SECRET_KEY
    value: EV[1:zqiRIeaaYK/NqctZDYzy6t0pTrtRDeq8:wqGpZRrsKN5nPhWQrS479cfBiXT0WQ==]
    type: secret
alerts:
  - rule: CPU_UTILIZATION
    disabled: false
    operator: GREATER_THAN
    value: 75
    window: FIVE_MINUTES
ingress:
  rules:
    - match:
        path:
          prefix: /api
      component:
        name: web-service
        preserve_path_prefix: true
        rewrite: /api
      redirect:
        uri: /developers
        authority: alarm.com
        port: 5050
        scheme: https
        redirect_code: 302
      cors:
        allow_origins:
          - exact:  https://alarm.com
            regex: ^https://alarm.com$
        allow_methods: ["GET", "POST"]
        allow_headers: ["Authorization"]
        expose_headers: ["Authorization"]
        max_age: 5h30m
        allow_credentials: true
maintenance:
  enabled: false